[project]
name = "cake-bakery-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.3",
    "django-browser-reload>=1.18.0",
    "django-tailwind[reload]>=4.0.1",
    "tailwind>=3.1.5b0",
]
